### ISSUE TITLE
Dynamo Print Funciton

### ISSUE THREAD

**Issue by hayden-wright-mottmac** [mottmacdonaldglobal/Sandbox#15]
It would be great to have a standalone printer function with custom inputs and and pdf drawing output within dynamo / revit. This would negate the need for us to use license based plugins. 

See below issue from the dynamo script I have created to do this function as a first pass.

https://github.com/mottmacdonaldglobal/dynamo_print_drawings/issues/1

**Comment by sonomirco** [comment]
These links could be useful
https://danimosite.wordpress.com/2019/09/15/placing-multiple-views-on-multiple-sheet-and-a-legend-copier/#Sheet.GetViewsAndLocations

https://danimosite.wordpress.com/2017/05/29/grids-propagate-extents/

**Comment by sonomirco** [comment]
I don't see the point to add it to Sandbox, because I can extract the code used to print, but in any case, you need other 4/5 nodes used to define print settings, views, etc etc.

Wrapping all the nodes into one is not ideal, and make a node only for printing but you need another bunch of nodes to extract other information that is already in the libraries you are using, and I really don't see the point to re-do the same thing.
