### ISSUE TITLE
Add 'bake' to layer component

### ISSUE THREAD

**Issue by charlie-mottmac** [mottmacdonaldglobal/Sandbox#68]
Would be helpful if there was a node that allowed you to input the geometry, layer name and layer colour, controlled by a boolean toggle

**Comment by sonomirco** [comment]
@charlie-mottmac the component that you are describing is `Bake` of `Elefront`.
`Bake` in Elefron bake the geometry in the level and color you want and also other properties.
https://grasshopperdocs.com/components/elefront/bakeObjects.html

**Comment by charlie-mottmac** [comment]
I'm confused. I already have a bake componet I've made with python but I thought the point of Sandbox was to have a consolidated group of nodes so we don't need plug-ins

**Comment by sonomirco** [comment]
Yes, but we can't also rewrite components that are part of libraries that are known and well be established.
I always said we should limit the use of external plugins as much as possible not avoid them, otherwise, we should re-write all the libraries!
Also, Sandbox is here to capture logic, IP, that are part of how teams work during projects.
It is the same situation that we got with the camera capture, we thought to develop a node for GH, but it is already implemented into Ladybug so what is the point to make it again.

We should have a basic list example (Ladybug, Elefront, Speckle) Geometry Gym still a question mark for me, and we should evaluate from time to time when is better to use a new one.

Also Human has the component `Bake` that does the same thing.
https://grasshopperdocs.com/components/human/bakeGeometry.html

So I think a good point from this conversation is to extract the basic list of plugins.
